[package]
name = "quickscript"
version = "0.6.0"
repository = "https://github.com/RedstoneWizard08/QuickScript"
authors = ["RedstoneWizard08", "td5032"]
description = "A quick programming language with a compiler implemented in Rust."
license = "MIT"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
clap = { version = "4.5.1", features = ["derive"] }
clap-verbosity-flag = "2.2.0"
clap_complete = "4.5.0"
const_format = "0.2.32"
cranelift-codegen = { version = "0.104.1", features = ["all-arch", "anyhow", "core", "bincode", "disas"] }
cranelift-frontend = "0.104.1"
cranelift-jit = "0.104.1"
cranelift-module = "0.104.1"
cranelift-native = "0.104.1"
cranelift-object = "0.104.1"
log = "0.4.20"
notify = "6.1.1"
object = "0.32.2"
pretty_env_logger = "0.5.0"
rand = "0.8.5"
target-lexicon = "0.12.13"
tempfile = "3.10.0"
which = "6.0.0"
thiserror = "1.0.57"

[target.'cfg(target_os = "windows")'.dependencies]
lnk = "0.5.1"

[[bin]]
name = "qsc"
path = "src/main.rs"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
