[package]
name = "qsc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.24", features = ["derive"] }
clap_complete = "4.3.2"
lazy_static = "1.4.0"
serde = { version = "1.0.185", features = ["derive"] }
serde_json = "1.0.105"

[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio = { version = "1.32.0", features = ["sync", "macros", "io-util", "rt", "time"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.32.0", features = ["full"] }
