[package]
name = "quickscript"
version = "0.2.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "qsc"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.75"
chic = "1.2.2"
clap = { version = "4.3.24", features = ["derive"] }
clap_complete = "4.3.2"
cranelift = { version = "0.100.0", features = ["core"] }
cranelift-codegen = { version = "0.100.0", features = ["all-arch", "anyhow", "core"] }
cranelift-frontend = "0.100.0"
cranelift-jit = "0.100.0"
cranelift-module = "0.100.0"
cranelift-native = "0.100.0"
cranelift-object = "0.100.0"
lazy_static = "1.4.0"
log = "0.4.20"
peg = "0.8.2"
rand = "0.8.5"
serde = { version = "1.0.185", features = ["derive"] }
serde_json = "1.0.105"
tracing-subscriber = "0.3.17"

[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio = { version = "1.32.0", features = ["sync", "macros", "io-util", "rt", "time"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.32.0", features = ["full"] }

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
