[package]
name = "quickscript"
version = "0.5.4"
repository = "https://github.com/RedstoneWizard08/QuickScript"
authors = ["RedstoneWizard08", "td5032"]
description = "A quick programming language with a compiler implemented in Rust."
license = "MIT"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.3.24", features = ["derive"] }
clap-verbosity-flag = "2.1.0"
clap_complete = "4.3.2"
const_format = "0.2.32"
cranelift = { version = "0.101.0", features = ["core"] }
cranelift-codegen = { version = "0.101.0", features = ["all-arch", "anyhow", "core", "bincode", "disas"] }
cranelift-frontend = "0.101.0"
qsc-cranelift-jit = { version = "0.104.0", path = "jit" }
cranelift-module = "0.101.0"
cranelift-native = "0.101.0"
cranelift-object = "0.101.0"
log = "0.4.20"
notify = "6.1.1"
object = "0.32.1"
phf = { version = "0.11.2", features = ["macros"] }
pretty_env_logger = "0.5.0"
rand = "0.8.5"
target-lexicon = "0.12.12"
tempfile = "3.8.1"
which = "5.0.0"

[[bin]]
name = "qsc"
path = "src/main.rs"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

[workspace]
resolver = "2"
members = [
    "jit"
]
