[package]
name = "qsc-lsp"
version.workspace = true
repository.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
tower-lsp.workspace = true
