[package]
name = "qsc-tokenizer"
version.workspace = true
repository.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
thiserror = { workspace = true }
qsc-core = { workspace = true }
