[package]
name = "qsc-core"
version.workspace = true
repository.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
object = { workspace = true }
rand = { workspace = true }
